# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "kmaster" do |node|
  
    node.vm.box               = "ubuntu/focal64"
    node.vm.box_check_update  = false
    node.vm.box_version       = "20211015.0.0"
    node.vm.hostname          = "kmaster.example.com"

    node.vm.network "public_network", ip: "172.20.10.60"
  
    node.vm.provider :virtualbox do |v|
      v.name    = "kmaster-test"
      v.memory  = 4096
      v.cpus    =  2
    end

    node.vm.provision "shell", path: "bootstrap_kmaster.sh"
  
  end  

end
